version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: astu-postgres
    environment:
      POSTGRES_DB: astudb
      POSTGRES_USER: astuuser
      POSTGRES_PASSWORD: astupass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - astu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U astuuser -d astudb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: astu-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/astudb
      SPRING_DATASOURCE_USERNAME: astuuser
      SPRING_DATASOURCE_PASSWORD: astupass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - astu-network

volumes:
  postgres_data:

networks:
  astu-network:
    driver: bridge